version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: build
          command: cargo build --verbose
      - run:
          name: test
          command: cargo test --verbose
